
name: Run Selenium Test

on:
  push :
    branches: ["master"]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@3
        with:
          java-version: "11"
          cache: maven
         
      - uses: browser-actions/setup-chrome@latest
      - run: mvn clean test
