
name: Run Selenium Test

on:
  push :
    branches: ["master"]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          cache: maven
          distribution: "temurin"
      - uses: browser-actions/setup-chrome@latest
      - run:  eval $(/opt/homebrew/bin/brew shellenv)
      - run: mvn clean test
